export let jogadoras = [
    {
        id: 1,
        nome: "Maria",
        sobrenome: "Silva",
        senha: "123456",
        dataDeNascimento: "2000-01-01",
        posicao: "Atacante",
        foto: "https://www.esportelandia.com.br/wp-content/uploads/2020/03/alex-morgan.jpg",
        email: "maria@email.com",
        telefone: "11999999999",
        condicaoMedica: false,
        possuiTime: false,
        tipo: "jogadora",
        pedido: true,
    },
    {
       id: 2,
        nome: "Luana",
        sobrenome: "Maluf",
        senha: "palmeiras",
        dataDeNascimento: "1994-08-09",
        posicao: "Atacante",
        foto: "https://vejasp.abril.com.br/wp-content/uploads/2022/07/Lupi-Bar-037-1.jpg-1.jpg?quality=70&strip=info&w=918&w=636",
        email: "luana@email.com",
        telefone: "11999999999",
        condicaoMedica: false,
        possuiTime: false,
        tipo: "jogadora",
        pedido: true,
    },
    {
       id: 3,
        nome: "Lana",
        sobrenome: "Maluf",
        senha: "palmeiras",
        dataDeNascimento: "1994-08-09",
        posicao: "Atacante",
        foto: "https://vejasp.abril.com.br/wp-content/uploads/2022/07/Lupi-Bar-037-1.jpg-1.jpg?quality=70&strip=info&w=918&w=636",
        email: "luana@email.com",
        telefone: "11999999999",
        condicaoMedica: false,
        possuiTime: false,
        tipo: "jogadora",
        pedido: true,
    }
]