export let jogos = [
  {
    id: "1",
    dataNumber: "Fev",
    dayNumber: "8",
    timeCasa: "SPFC",
    logoCasa: "https://logodetimes.com/times/sao-paulo/logo-sao-paulo-4096.png",
    golsCasa: 2,
    timeFora: "SFC",
    logoFora: "https://logodetimes.com/times/santos/logo-santos-1536.png",
    golsFora: 0,
    estadio: "Morumbi",
    hora: "21:30",
    hashtag: "#ChoqueDeGigantes",
    futuro: false,
    exibir: false
  },
  {
    id: "2",
    dataNumber: "Fev",
    dayNumber: "15",
    timeCasa: "Corinthians",
    logoCasa: "https://logodetimes.com/times/corinthians/logo-corinthians-4096.png",
    golsCasa: 3,
    timeFora: "Palmeiras",
    logoFora: "https://imagepng.org/wp-content/uploads/2018/03/escudo-palmeiras.png",
    golsFora: 2,
    estadio: "Neo Química Arena",
    hora: "20:00",
    hashtag: "#DerbyPaulista",
    futuro: false,
    exibir: true
  },
  {
    id: "3",
    dataNumber: "Fev",
    dayNumber: "1",
    logoCasa: "https://th.bing.com/th/id/R.c7f858adcf5c6f5cd97f4b2a263cd5b1?rik=eksXhOCTAYsIrg&pid=ImgRaw&r=0",
    golsCasa: 1,
    timeFora: "Vasco",
    logoFora: "https://tse4.mm.bing.net/th/id/OIP.rnihwMvzGnzLsELBY_PE3wHaHa?rs=1&pid=ImgDetMain&o=7&rm=3",
    golsFora: 1,
    estadio: "Maracanã",
    hora: "18:00",
    hashtag: "#ClassicoCarioca",
    futuro: false,
    exibir: true
  },
];
