export let pedidos = [
    {
    id: 11,
    nome: "Ana",
    sobrenome: "Costa",
    senha: "ana123",
    dataDeNascimento: "2002-03-22",
    posicao: "Meio-campo",
    foto: null,
    email: "ana@email.com",
    telefone: "11988888888",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 12,
    nome: "Beatriz",
    sobrenome: "Mendes",
    senha: "bea456",
    dataDeNascimento: "2001-11-15",
    posicao: "Atacante",
    foto: null,
    email: "beatriz@email.com",
    telefone: "11977777777",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 13,
    nome: "Juliana",
    sobrenome: "Ferreira",
    senha: "juli789",
    dataDeNascimento: "2003-06-18",
    posicao: "Zagueira",
    foto: null,
    email: "juliana@email.com",
    telefone: "11966666666",
    condicaoMedica: true,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 14,
    nome: "Larissa",
    sobrenome: "Pereira",
    senha: "lari321",
    dataDeNascimento: "2000-08-08",
    posicao: "Meio-campo",
    foto: null,
    email: "larissa@email.com",
    telefone: "11955555555",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 15,
    nome: "Camila",
    sobrenome: "Rodrigues",
    senha: "camila654",
    dataDeNascimento: "2002-10-10",
    posicao: "Zagueira",
    foto: null,
    email: "camila@email.com",
    telefone: "11944444444",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 16,
    nome: "Patrícia",
    sobrenome: "Nascimento",
    senha: "pat789",
    dataDeNascimento: "2001-01-20",
    posicao: "Atacante",
    foto: null,
    email: "patricia@email.com",
    telefone: "11933333333",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 17,
    nome: "Isabela",
    sobrenome: "Monteiro",
    senha: "isa456",
    dataDeNascimento: "2003-07-07",
    posicao: "Meio-campo",
    foto: null,
    email: "isabela@email.com",
    telefone: "11922222222",
    condicaoMedica: true,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 18,
    nome: "Renata",
    sobrenome: "Dias",
    senha: "renata123",
    dataDeNascimento: "2000-09-09",
    posicao: "Zagueira",
    foto: null,
    email: "renata@email.com",
    telefone: "11911111111",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 19,
    nome: "Tatiane",
    sobrenome: "Cunha",
    senha: "tat321",
    dataDeNascimento: "2001-12-12",
    posicao: "Meio-campo",
    foto: null,
    email: "tatiane@email.com",
    telefone: "11900000000",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 20,
    nome: "Fernanda",
    sobrenome: "Almeida",
    senha: "fernanda456",
    dataDeNascimento: "1999-04-04",
    posicao: "Goleira",
    foto: null,
    email: "fernanda@email.com",
    telefone: "11899999999",
    condicaoMedica: true,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 21,
    nome: "Sabrina",
    sobrenome: "Martins",
    senha: "sab654",
    dataDeNascimento: "2002-02-02",
    posicao: "Atacante",
    foto: null,
    email: "sabrina@email.com",
    telefone: "11888888888",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 22,
    nome: "Débora",
    sobrenome: "Souza",
    senha: "deb321",
    dataDeNascimento: "2000-06-06",
    posicao: "Zagueira",
    foto: null,
    email: "debora@email.com",
    telefone: "11877777777",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 23,
    nome: "Nicole",
    sobrenome: "Barros",
    senha: "nico789",
    dataDeNascimento: "2003-03-03",
    posicao: "Meio-campo",
    foto: null,
    email: "nicole@email.com",
    telefone: "11866666666",
    condicaoMedica: true,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 24,
    nome: "Aline",
    sobrenome: "Teixeira",
    senha: "aline123",
    dataDeNascimento: "2001-05-05",
    posicao: "Atacante",
    foto: null,
    email: "aline@email.com",
    telefone: "11855555555",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 25,
    nome: "Monique",
    sobrenome: "Ramos",
    senha: "monique456",
    dataDeNascimento: "2000-07-07",
    posicao: "Zagueira",
    foto: null,
    email: "monique@email.com",
    telefone: "11844444444",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 26,
    nome: "Vanessa",
    sobrenome: "Vieira",
    senha: "vanessa789",
    dataDeNascimento: "2002-01-01",
    posicao: "Meio-campo",
    foto: null,
    email: "vanessa@email.com",
    telefone: "11833333333",
    condicaoMedica: true,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 27,
    nome: "Letícia",
    sobrenome: "Cavalcante",
    senha: "leti321",
    dataDeNascimento: "2003-08-08",
    posicao: "Goleira",
    foto: null,
    email: "leticia@email.com",
    telefone: "11822222222",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  },
  {
    id: 28,
    nome: "Bruna",
    sobrenome: "Lopes",
    senha: "bruna654",
    dataDeNascimento: "2001-09-09",
    posicao: "Atacante",
    foto: null,
    email: "bruna@email.com",
    telefone: "11811111111",
    condicaoMedica: false,
    possuiTime: false,
    tipo: "jogadora",
    pedido: false
  }
]