export let pedidosTimes = [
{
    id: 51,
    nome: "Fênix Dourada",
    senha: "senhafenix",
    cidade: "Rio de Janeiro",
    responsavel: "Juliana Lima",
    email: "juliana@fenixdourada.com",
    telefone: "21988887777",
    numero: 12,
    foto: "https://tse1.mm.bing.net/th/id/OIP.8YxK7ZKXzZzvZKZKZKZKZQHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 52,
    nome: "Águias do Sul",
    senha: "aguias2023",
    cidade: "Porto Alegre",
    responsavel: "Fernanda Costa",
    email: "fernanda@aguiasdossul.com",
    telefone: "51977776666",
    numero: 20,
    foto: "https://tse2.mm.bing.net/th/id/OIP.3KxK3KxK3KxK3KxK3KxK3KxHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 53,
    nome: "Leonas FC",
    senha: "leonasfc2024",
    cidade: "Belo Horizonte",
    responsavel: "Carla Mendes",
    email: "carla@leonasfc.com",
    telefone: "31966665555",
    numero: 15,
    foto: "https://tse3.mm.bing.net/th/id/OIP.KxKxKxKxKxKxKxKxKxKxKxHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 54,
    nome: "Panteras Negras",
    senha: "panteras123",
    cidade: "Curitiba",
    responsavel: "Tatiane Rocha",
    email: "tatiane@panterasnegras.com",
    telefone: "41955554444",
    numero: 17,
    foto: "https://tse1.mm.bing.net/th/id/OIP.XxXxXxXxXxXxXxXxXxXxXxHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 55,
    nome: "Guerreiras do Norte",
    senha: "guerreiras2025",
    cidade: "Manaus",
    responsavel: "Isabela Nunes",
    email: "isabela@guerreirasdn.com",
    telefone: "92944443333",
    numero: 14,
    foto: "https://tse2.mm.bing.net/th/id/OIP.YyYyYyYyYyYyYyYyYyYyYyHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 56,
    nome: "Rainhas da Bola",
    senha: "rainhas2022",
    cidade: "Recife",
    responsavel: "Monique Oliveira",
    email: "monique@rainhasdabola.com",
    telefone: "81933332222",
    numero: 16,
    foto: "https://tse3.mm.bing.net/th/id/OIP.ZzZzZzZzZzZzZzZzZzZzZzHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 57,
    nome: "Valquírias FC",
    senha: "valquiriasfc",
    cidade: "Fortaleza",
    responsavel: "Renata Dias",
    email: "renata@valquiriasfc.com",
    telefone: "85922221111",
    numero: 13,
    foto: "https://tse1.mm.bing.net/th/id/OIP.AaAaAaAaAaAaAaAaAaAaAaHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 58,
    nome: "Amazonas FC",
    senha: "amazonas2021",
    cidade: "Belém",
    responsavel: "Letícia Monteiro",
    email: "leticia@amazonasfc.com",
    telefone: "91911110000",
    numero: 19,
    foto: "https://tse2.mm.bing.net/th/id/OIP.BbBbBbBbBbBbBbBbBbBbBbHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  },
  {
    id: 59,
    nome: "Império Feminino",
    senha: "imperio2020",
    cidade: "Brasília",
    responsavel: "Bruna Ribeiro",
    email: "bruna@imperiofeminino.com",
    telefone: "61900009999",
    numero: 11,
    foto: "https://tse3.mm.bing.net/th/id/OIP.CcCcCcCcCcCcCcCcCcCcCcHaHa?rs=1&pid=ImgDetMain",
    jogadoras: [],
    candidatas: [],
    tipo: "time",
    pedido: false
  }

]